apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fish-bowl-data
  namespace: minecraft
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: fish-bowl-storageclass
  resources:
    requests:
      storage: 20Gi
