apiVersion: v1
kind: Service
metadata:
  name: oneblock
  namespace: minecraft-oneblock
spec:
  selector:
    app: oneblock
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  type: ClusterIP
