audiobookshelf:
  nfs:
  - server: truenas.parkiki.org
    storage: 100Gi
    name: media
    share:
      - name: audiobooks
        path: /mnt/fast_storage/k3s/audiobookshelf/audiobooks
        mountPath: /audiobooks
        readOnly: true
