couchdb:
  clusterSize: 1
  createAdminSecret: false
  extraSecretName: couchdb-credentials

  couchdbConfig:
    couchdb:
      uuid: c66119ac-4726-4f00-a568-39ce81cd89c1

  persistentVolume:
    enabled: true
    existingClaims:
      - couchdb-pvc
