---
apiVersion: v1
kind: Namespace
metadata:
  name: couchdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-iscsi
  iscsi:
    targetPortal: 192.168.1.232:3260
    iqn: iqn.2005-10.org.freenas.ctl:couchdb
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage-couchdb-0 
  namespace: couchdb
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
  volumeName: couchdb-pv # Still perfectly maps to your manual PV
