---
apiVersion: v1
kind: Namespace
metadata:
  name: couchdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-iscsi
  iscsi:
    targetPortal: 192.168.1.232:3260
    iqn: iqn.2005-10.org.freenas.ctl:couchdb
    lun: 0
    fsType: ext4
    readOnly: false
