apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: couchdb-svc-couchdb
  namespace: couchdb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`couchdb.parkiki.org`)
      kind: Rule
      services:
        - name: couchdb-svc-couchdb
          port: 5984
  tls:
    certResolver: letsencrypt
